name: Build and Test

on: [pull_request]

jobs:
  build-tinybar:
    name: Build & Test
    runs-on: macos-11

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.4.2

      - name: Install python dependencies
        run: poetry install

      - uses: pre-commit/action@v3.0.0
        name: "Linters and formatters check"
        with:
          extra_args: --all-files --show-diff-on-failure

      - name: Build TinyBar.app
        run: PYTHONPATH="." poetry run python3 setup.py py2app
